services:
    db:
        image: postgres:17-alpine
        container_name: postgres_db
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: root
            POSTGRES_DB: contabilidade
        ports:
          - "5433:5432"
        volumes:
          - postgres_data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 5s
            timeout: 5s
            retries: 5
        restart: unless-stopped

    app:
        image: pedrohens/contabilidade-app:latest
        container_name: contabilidade_pdf_app
        ports:
          - "8080:8080"
        depends_on:
          - db
        environment:
            SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/contabilidade
            SPRING_DATASOURCE_USERNAME: postgres
            SPRING_DATASOURCE_PASSWORD: root
            SPRING_JPA_HIBERNATE_DDL_AUTO: validate
        restart: unless-stopped

volumes:
    postgres_data:
    
