name: Java CI with Maven (H2)

on: [push, pull_request]  # Dispara em pushes e pull requests

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'  # Cacheia as dependências do Maven

      - name: Run tests with H2
        run: mvn clean test
